### ISSUE TITLE
Add an important note to readme

### ISSUE THREAD

**Issue by techn0tr0ll** [SequoiaSan/Guide-How-To-Upload-bin-to-ESP8266-ESP32#1]
Hey there

i was struggling a lot to flash my firmware cause the tool was stuck in "SYNC"

After searching some other instructions i found the information, that the BOOT button has to be pressed while connecting the dev board to the usb port to detect the board as the right one and to show the right COM Port.

I would suggest to add this information to your instruction - then it would be even better as it is right now :)

Never the less, thx for your instruction ^^

**Comment by SequoiaSan** [comment]
Hey!

Thanks for taking your time to write this one. It's a good point! I'll add this to the guide 🙂

**Comment by SequoiaSan** [comment]
Added note. Thanks again!
